[package]
name = "observability"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-cloudwatchlogs = "1"
regex = "1"
serde_json = "1"
tracing = "0.1"
tracing-cloudwatch = { version = "0.4", features = ["awssdk"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

[dev-dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
