[package]
name = "control-plane"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[features]
enclave = []

[dependencies]
clap = { version = "4", features = ["derive"] }
observability = { path = "../observability" }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1"
anyhow = "1"
